
version: '3'

services:
  caddy:
    image: abiosoft/caddy:1.0.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/caddy/Caddyfile:/etc/Caddyfile"
      - "${DATA_DIRECTORY}/caddy/.caddy:/root/.caddy"
    environment:
      EULA: "ACME_AGREE=true"
    restart: on-failure
    networks:
      - services
    depends_on:
      - confluence
      - jira

  jira:
    image: atlassian/jira-software:8.9.0-EAP02-jdk11
    volumes:
      - ${DATA_DIRECTORY}/jira:/var/atlassian/application-data/jira
    environment:
      #Proxy
      - ATL_PROXY_NAME=jira.swarmus.jajservers.duckdns.org
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    restart: on-failure
    expose: 
      - "8080"
    ports:
      - "587:587"
      - "465:465"
    networks:
      - db-jira
      - db-easyBI
      - services
    depends_on:
      - jira-postgresql
      - easyBI-postgresql

  confluence: 
    build: 
      context: .
      dockerfile: confluence-dockerfile
    # Allows naming the build
    image: confluence_swarmus_latex:latest
    volumes:
      - ${DATA_DIRECTORY}/confluence:/var/atlassian/application-data/confluence
    environment:
      #Proxy
      - ATL_PROXY_NAME=confluence.swarmus.jajservers.duckdns.org
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    restart: on-failure
    expose:
      - "8090"
    networks:
      - db-confluence
      - db-easyBI
      - services
    depends_on:
      - confluence-postgresql
      - easyBI-postgresql
      - jira

  jira-postgresql:
    image: postgres:9.6-alpine
    restart: on-failure
    networks:
      - db-jira
    volumes:
      - ${DATA_DIRECTORY}/jira-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${JIRA_DB_PASSWORD}
      - POSTGRES_USER=${JIRA_DB_USER}
      - POSTGRES_DB=${JIRA_DB}
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C

  confluence-postgresql:
    image: postgres:9.6-alpine
    restart: on-failure
    networks:
      - db-confluence
    volumes:
      - ${DATA_DIRECTORY}/confluence-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${CONFLUENCE_DB_PASSWORD}
      - POSTGRES_USER=${CONFLUENCE_DB_USER}
      - POSTGRES_DB=${CONFLUENCE_DB}
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C

  easyBI-postgresql:
    image: postgres:9.6-alpine
    restart: on-failure
    networks:
      - db-easyBI
    volumes:
      - ${DATA_DIRECTORY}/easyBI-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${EASYBI_DB_PASSWORD}
      - POSTGRES_USER=${EASYBI_DB_USER}
      - POSTGRES_DB=${EASYBI_DB}
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C

  onedrive-swarmus:
    image: driveone/onedrive:alpine-202005291951
    restart: on-failure
    volumes: 
      - ${DATA_DIRECTORY}/onedrive:/onedrive/conf
      - "${BACKUP_DIRECTORY}:/onedrive/data"

volumes:
  onedrive:
    external:
      name: "onedrive_SwarmUS"

networks:
  services:
    driver: bridge
  db-jira:
    driver: bridge
  db-confluence:
    driver: bridge
  db-easyBI:
    driver: bridge