
version: '3'

services:
  caddy:
    image: abiosoft/caddy:1.0.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/caddy/Caddyfile:/etc/Caddyfile"
      - "${DATA}/caddy/.caddy:/root/.caddy"
    environment:
      EULA: "ACME_AGREE=true"
    restart: on-failure
    networks:
      - services
    depends_on:
      - confluence
      - jira

  jira:
    image: atlassian/jira-software:8.9.0-EAP02-jdk11
    volumes:
      - ${DATA}/jira:/var/atlassian/application-data/jira
    environment:
      #Proxy
      - ATL_PROXY_NAME=caddy
      - ATL_PROXY_PORT=8080
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    restart: on-failure
    expose: 
      - "8080"
    networks:
      - db-jira
      - services
    depends_on:
      - jira-postgresql

  confluence: 
    image: atlassian/confluence-server:6.6.15-jdk8
    volumes:
      - ${DATA}/confluence:/var/atlassian/application-data/confluence
    environment:
      #Proxy
      - ATL_PROXY_NAME=caddy
      - ATL_PROXY_PORT=8090
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    restart: on-failure
    expose:
      - "8090"
    networks:
      - db-confluence
      - services
    depends_on:
      - confluence-postgresql

  jira-postgresql:
    image: postgres:9.4-alpine
    restart: on-failure
    networks:
      - db-jira
    volumes:
      - ${DATA}/jira-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${JIRA_DB_PASSWORD}
      - POSTGRES_USER=${JIRA_DB_USER}
      - POSTGRES_DB=${JIRA_DB}
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C

  confluence-postgresql:
    image: postgres:9.6-alpine
    restart: on-failure
    networks:
      - db-confluence
    volumes:
      - ${DATA}/confluence-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${CONFLUENCE_DB_PASSWORD}
      - POSTGRES_USER=${CONFLUENCE_DB_USER}
      - POSTGRES_DB=${CONFLUENCE_DB}
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C

networks:
  services:
    driver: bridge
  db-jira:
    driver: bridge
  db-confluence:
    driver: bridge